### ISSUE TITLE
Weird Text when using commands

### ISSUE THREAD

**Issue by Deafpie** [MarkusBordihn/BOs-Lobby#20] opened 2023-12-08 22:27 UTC
**Describe the bug**
When doing /lobby, it says things like:
text.lobby.teleport_remaining
text.lobby.teleport_remaining
text.lobby.teleport_remaining
text.lobby.teleport_remaining
text.lobby.failed_cooldown
text.lobby.teleport_abort

here is an example: https://prnt.sc/UczD9Y5jipHb

How do I change these?
thanks!

**Comment by MarkusBordihn** [comment] 2023-12-08 22:47
Duplicate of #19

**Closed as completed by MarkusBordihn** 2023-12-08 22:47 UTC
Labels: duplicate
